# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Academy Furniture and Supply Blog
header-img: img/home-bg.jpg
email: info@academyfurn.com
description: > # this means to ignore newlines until "baseurl:"
  Keeping you updated on the current news in Educator Furniture and Development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://secure-peak-30091.herokuapp.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: academyfurn
github_username:  academyfurn
facebook_username:  ouracad
email_username:  info@academyfurn.com
copyright_name: Academy Furniture and Supplies
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: https://www.facebook.com/ouracad/


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5

theme: minima # this doesnt need to be included
gems:
  - jekyll-feed
  - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","config.ru","Gemfile","Gemfile.lock","vendor"]
